CSV_FILE_PATH = "tiny_ted_data.csv"

INDEX_NAME = "tiny-ted"
EMBEDDING_MODEL = "RPRTHPB-text-embedding-3-small"
CHAT_MODEL = "RPRTHPB-gpt-5-mini"

DEFAULT_CHUNK_SIZE = 1000
DEFAULT_OVERLAP = 150
DEFAULT_RETRIEVE_TOP_K = 8